[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "didit-aml-log"
version = "0.0.1"
description = "Didit AML Log"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
